spring:
  datasource:
    # jdbc_config   datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password
    # 默认连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cache:
    jcache:
      config: classpath:ehcache.xml
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto-hotswapping.html
  thymeleaf:
    cache: false
  # 关闭默认favicon
  mvc:
    favicon:
      enabled: false
# 控制台打印执行的SQL cn.ufan0.blog_test.mapper
logging:
  level:
    cn:
      ufan0:
        blog_test:
          mapper: debug
#  security:
#    user:
#      name: admin
#      password: 123
#  servlet:
#    multipart:
#      max-request-size: 1MB
#      max-file-size: 10MB